name: test

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/test.yml'
      - '.github/workflows/shellcheck.yml'
      - '.github/workflows/mcp_gateway_test.yml'

permissions:
  contents: read

jobs:
  shellcheck:
    if: github.repository_owner == 'hwdsl2'
    uses: ./.github/workflows/shellcheck.yml

  mcp_gateway_test:
    if: github.repository_owner == 'hwdsl2'
    uses: ./.github/workflows/mcp_gateway_test.yml